task_manager/labels/urls.py
from django.urls import path
from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='index'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/statuses/urls.py
from django.urls import path
from task_manager.statuses import views

app_name = 'statuses'

urlpatterns = [
    path('', views.StatusListView.as_view(), name='index'),
    path('create/', views.StatusCreateView.as_view(), name='create'),
    path('<pk>/update/', views.StatusUpdateView.as_view(), name='update'),
    path('<pk>/delete/', views.StatusDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [

    path('', views.TaskListView.as_view(), name='index'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<pk>/', views.TaskView.as_view(), name='task'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager import views
from task_manager.users.views import UserLoginView, UserLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),

    path('users/', include('task_manager.users.urls')),

    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),

    path('statuses/', include('task_manager.statuses.urls')),

    path('tasks/', include('task_manager.tasks.urls')),

    path('labels/', include('task_manager.labels.urls')),

]

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='index'),
    path('create/', views.UsersCreateView.as_view(), name='create'),
    path('<pk>/update/', views.UsersUpdateView.as_view(), name='update'),
    path('<pk>/delete/', views.UsersDeleteView.as_view(), name='delete'),
]

task_manager/labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(max_length=90, unique=True, verbose_name=_('Name'))

    def __str__(self):
        return self.name

task_manager/models.py
from django.db import models
from django.conf import settings


class Status(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class Label(models.Model):
    name = models.CharField(max_length=90, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=90)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    reporter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="reporter_id")
    assignee = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="assignee_id")
    labels = models.ManyToManyField(Label, through='TaskLabel', through_fields=('task', 'label'))

    def get_absolute_url(self):
        return "/tasks/%i/" % self.id


class TaskLabel(models.Model):
    task = models.ForeignKey(Task, on_delete=models.PROTECT)
    label = models.ForeignKey(Label, on_delete=models.PROTECT)

task_manager/statuses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Status(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name=_('Name'))

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models

from task_manager.statuses.models import Status
from task_manager.labels.models import Label
from django.utils.translation import gettext_lazy as _

from task_manager.users.models import User


class Task(models.Model):
    name = models.CharField(max_length=90, verbose_name=_('Name'))
    status = models.ForeignKey(Status, on_delete=models.PROTECT, verbose_name=_('Status'))
    description = models.TextField(verbose_name=_('Description'))
    date = models.DateTimeField(auto_now_add=True)
    reporter = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="reporter_id",
        verbose_name=_('Reporter')
    )
    executor = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="assignee_id",
        blank=True,
        null=True,
        verbose_name=_('Assignee')
    )
    labels = models.ManyToManyField(
        Label,
        through='TaskLabel',
        through_fields=('task', 'label'),
        blank=True,
        verbose_name=_('Labels')
    )

    def get_absolute_url(self):
        return "/tasks/%i/" % self.id


class TaskLabel(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.PROTECT)

task_manager/users/models.py
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django import forms


class User(User):
    def __str__(self):
        return self.get_full_name()


class UserForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        label=_('First Name')
    )
    last_name = forms.CharField(
        required=True,
        label=_("Second Name")
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name', 'last_name')

task_manager/labels/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import ProtectedError
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy

from task_manager.labels.models import Label


class LabelListView(LoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/label_list.html'


class LabelCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Label
    fields = ['name']
    template_name = 'labels/label_create.html'
    success_url = reverse_lazy('labels:index')
    success_message = _('Label created')


class LabelUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    fields = ['name']
    template_name = 'labels/label_update.html'
    success_url = reverse_lazy('labels:index')
    success_message = _('Label updated')


class LabelDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Label
    template_name = 'labels/label_delete.html'
    success_url = reverse_lazy('labels:index')
    success_message = _('Label deleted')

    def post(self, request, *args, **kwargs):
        try:
            return super().post(request, *args, **kwargs)
        except ProtectedError:
            messages.error(self.request, _('Unable to delete label because it is in use'))
            return redirect('labels:index')

task_manager/statuses/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import ProtectedError
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy

from task_manager.statuses.models import Status


class StatusListView(LoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/status_list.html'


class StatusCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Status
    fields = ['name']
    template_name = 'statuses/status_create.html'
    success_url = reverse_lazy('statuses:index')
    success_message = _('Status created')


class StatusUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    fields = ['name']
    template_name = 'statuses/status_update.html'
    success_url = reverse_lazy('statuses:index')
    success_message = _('Status updated')


class StatusDeleteView(SuccessMessageMixin, DeleteView):
    model = Status
    template_name = 'statuses/status_delete.html'
    success_url = reverse_lazy('statuses:index')
    success_message = _('Status deleted')

    def post(self, request, *args, **kwargs):
        try:
            return super().post(request, *args, **kwargs)
        except ProtectedError:
            messages.error(self.request, _('Unable to delete status because it is in use'))
            return redirect('statuses:index')

task_manager/tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django_filters import FilterSet, BooleanFilter, ModelChoiceFilter
from django.utils.translation import gettext_lazy as _
from django_filters.views import FilterView
from django import forms

from task_manager.labels.models import Label
from task_manager.tasks.models import Task
from task_manager.users.models import User


class TaskFilter(FilterSet):
    created_by_me = BooleanFilter(
        field_name='creator',
        label=_('Created by me'),
        widget=forms.CheckboxInput,
        method='filter_self_tasks',

    )

    label = ModelChoiceFilter(
        queryset=Label.objects.all(),
        field_name='labels',
        label=_('Label'),
    )

    def filter_self_tasks(self, queryset, name, value):
        if not value:
            return queryset

        return queryset.filter(reporter=self.request.user)

    class Meta:
        model = Task

        fields = ['status', 'executor', 'label', 'created_by_me']


class TaskListView(LoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/tasks_list.html'
    filterset_class = TaskFilter


class TaskView(DetailView):
    model = Task

    template_name = 'tasks/task_detail.html'


class TaskCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    fields = ['name', 'status', 'description', 'executor', 'labels']
    template_name = 'tasks/task_create.html'
    success_message = _('Task created')
    success_url = reverse_lazy('tasks:index')

    def form_valid(self, form):
        user = self.request.user
        form.instance.reporter = User.objects.get(id=user.id)
        return super(TaskCreateView, self).form_valid(form)


class TaskUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    fields = ['name', 'status', 'description', 'executor', 'labels']
    template_name = 'tasks/task_update.html'
    success_message = _('Task updated')
    success_url = reverse_lazy('tasks:index')


class TaskDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Task
    template_name = 'tasks/task_delete.html'
    success_url = reverse_lazy('tasks:index')
    success_message = _('Task deleted')

    def dispatch(self, request, *args, **kwargs):
        if request.user.id != self.get_object().reporter.id:
            messages.error(self.request, _('A task can only be deleted by its author'))
            return redirect(reverse_lazy('tasks:index'))
        return super().dispatch(request, *args, **kwargs)

task_manager/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.views.generic import CreateView, DeleteView, UpdateView, ListView

from task_manager.users.models import UserForm, User


class UserListView(ListView):
    model = User
    template_name = 'users/users.html'


class UsersCreateView(SuccessMessageMixin, CreateView):
    form_class = UserForm
    template_name = 'users/users_create.html'
    success_url = reverse_lazy('login')
    success_message = _('User successfully registered')


class UsersUpdateView(SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = 'users/users_update.html'
    success_url = reverse_lazy('users:index')
    success_message = _('User successfully updated')

    def dispatch(self, request, *args, **kwargs):
        if request.user.id != self.get_object().id:
            messages.error(self.request, _('You do not have permission to modify another user.'))
            return redirect(reverse_lazy('users:index'))

        return super().dispatch(request, *args, **kwargs)


class UsersDeleteView(SuccessMessageMixin, DeleteView):
    model = User
    template_name = 'users/users_delete.html'
    success_url = reverse_lazy('users:index')
    success_message = _('User successfully deleted')

    def dispatch(self, request, *args, **kwargs):
        if request.user.id != self.get_object().id:
            messages.error(self.request, _('You do not have permission to modify another user.'))
            return redirect(reverse_lazy('users:index'))
        return super().dispatch(request, *args, **kwargs)


class UserLoginView(SuccessMessageMixin, LoginView):
    template_name = 'users/users_login.html'
    next_page = reverse_lazy('index')
    success_message = _('You are logged in')


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.info(request, _('You are logged out'))
        return response

task_manager/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html', context={
    })

task_manager/templates/base.html
{% extends 'bootstrap.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block bootstrap4_content %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">{% translate "MenuNavigation" %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">{% translate "MenuHome" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:index' %}">{% translate "Users" %}</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'statuses:index' %}" >{% translate "Statuses" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tasks:index' %}" >{% translate "Tasks" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'labels:index' %}" >{% translate "Labels" %}</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">{% translate "Logout" %}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:create' %}">{% translate "Sign Up" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">{% translate "Log In" %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container pt-5 mt-5">

        <div class="starter-template">
            {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
            {% block content %}(no content){% endblock %}
        </div>

    </main>
{% endblock %}

task_manager/templates/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}{% block title %}{% endblock %}{% endblock %}

task_manager/templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}{% translate "Main page title" %}{% endblock %}

{% block content %}
    <h1>{% translate "Main page title" %}</h1>
    <p class="lead">{% translate "Main page description" %}</p>
{% endblock %}

task_manager/templates/users_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}{% translate "Sign Up" %}{% endblock %}

{% block content %}
<h1 class="pb-4">{% translate "Sign Up" %}</h1>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary">{% translate "Sign Up" %}</button>
</form>
{% endblock %}

task_manager/templates/users_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}{% translate "Delete" %}{% endblock %}

{% block content %}
<h1 class="pb-4">{% translate "Delete" %}</h1>
<form method="post">
    {% csrf_token %}
    <p>{% translate "Are you sure you want to delete" %} "{{ object }}"?</p>
    <button class="btn btn-primary">{% translate "Delete" %}</button>
</form>
{% endblock %}